[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message }} ([`{{ commit.id | truncate(length=7, end="") }}`]({{ commit.id }}))
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
commit_preprocessors = []
commit_parsers = [
  { message = "^feat",     group = "✨ Features" },
  { message = "^fix",      group = "🐛 Bug Fixes" },
  { message = "^sec",      group = "🔒 Security" },
  { message = "^perf",     group = "⚡ Performance" },
  { message = "^refactor", group = "♻️ Refactoring" },
  { message = "^test",     group = "🧪 Tests" },
  { message = "^chore",    group = "🔧 Maintenance" },
  { message = "^ci",       group = "🔧 Maintenance" },
  { message = "^build",    group = "🔧 Maintenance" },
  { message = "^docs",     group = "📚 Documentation" },
  { message = "^.*",       group = "🔧 Maintenance" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
